language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - v7
  - v6
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export CXX=g++-4.8; fi
  - npm install -g coveralls
script:
  - npm run test:lint
  - npm run test:coverage
after_success:
  - cat ./coverage/lcov.info | coveralls || echo 'Failed to upload to coveralls...'
  - npm run semantic-release
